<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //
    protected $table = 'student';

    protected $fillable = ['name','age','sex'];

    public $timestamps = true;

    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }

    public function fromDateTime($value)
    {
        return strtotime(parent::fromDateTime($value));
    }
}
