<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //指定表名
    protected $table = 'student';
    //指定主键
    protected  $primaryKey = 'id';

    //自动维护时间戳
    public $timestamps = false;

    //存时间戳
    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    //返回数据库中时间
    public function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }

    //指定允许批量赋值的字段
//    protected $fillable = ['name','age'];
    //指定不允许批量赋值的字段
    protected $guarded = [];
}